name: alarm_clock_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  circular_countdown_timer: 0.1.0
  flutter_datetime_picker: 1.5.0
  flutter_local_notifications: 7.0.0
  sqflite: 1.3.2
  dotted_border: ^2.0.0+1
  cupertino_icons: ^1.0.2
  stop_watch_timer: ^1.3.1
  intl: 0.16.1
  get: 3.26.0
  flutter: 
    sdk: flutter


dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

  fonts:
     - family: avenir
       fonts:
         - asset: assets/fonts/Avenir-Book.ttf
         - asset: assets/fonts/Avenir-Heavy.ttf
           weight: 700
         - asset: assets/fonts/Avenir-Medium.ttf
           weight: 500
         - asset: assets/fonts/Avenir-Light.ttf
           weight: 300
#           style: italic
#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/Avenir-Book.ttf
#         - asset: fonts/Avenir-Heavy.ttf
#         - asset: fonts/Avenir-Light.ttf
#         - asser: fonts/Avenir-Medium.ttf
#           weight: 700

